//! Development tooling for generated scanner and highlighting data.
use serde_json::{Value, json};
use std::{collections::BTreeSet, env, error::Error, fs, path::Path};

fn strings(rule: &Value, words: &mut BTreeSet<String>) {
    match rule {
        Value::Object(object) => {
            if object.get("type").and_then(Value::as_str) == Some("STRING") {
                words.insert(object["value"].as_str().unwrap().to_owned());
            }
            for value in object.values() {
                strings(value, words);
            }
        }
        Value::Array(values) => {
            for value in values {
                strings(value, words);
            }
        }
        _ => {}
    }
}

fn update(path: &str, contents: &str, check: bool) -> Result<(), Box<dyn Error>> {
    if check {
        if fs::read_to_string(path)? != contents {
            return Err(format!("{path} is stale; run cargo run --example generate").into());
        }
    } else {
        fs::write(path, contents)?;
    }
    Ok(())
}

fn import_builtins(path: &str) -> Result<(), Box<dyn Error>> {
    let mut vocabularies = serde_json::Map::new();
    for line in fs::read_to_string(path)?.lines() {
        let Some((_, rest)) = line.split_once("syn keyword factorWord_") else {
            continue;
        };
        let Some((vocabulary, words)) = rest.split_once(" contained ") else {
            continue;
        };
        if vocabulary == "syntax" {
            continue;
        }
        let words: BTreeSet<_> = words
            .split_whitespace()
            .map(|word| word.replace("\\|", "|"))
            .collect();
        vocabularies.insert(vocabulary.to_owned(), json!(words));
    }
    if vocabularies.is_empty() {
        return Err("No vocabulary lists found".into());
    }
    let data = json!({
        "source": "https://github.com/factor/factor.vim/blob/master/syntax/factor/generated.vim",
        "vocabularies": vocabularies,
    });
    fs::write(
        "data/builtins.json",
        serde_json::to_string_pretty(&data)? + "\n",
    )?;
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    env::set_current_dir(Path::new(env!("CARGO_MANIFEST_DIR")))?;
    let args: Vec<_> = env::args().skip(1).collect();
    let check = match args.as_slice() {
        [] => false,
        [option] if option == "--check" => true,
        [option, path] if option == "--import-builtins" => {
            import_builtins(path)?;
            false
        }
        _ => {
            return Err(
                "Usage: cargo run --example generate -- [--check | --import-builtins PATH]".into(),
            );
        }
    };
    let grammar: Value = serde_json::from_str(&fs::read_to_string("src/grammar.json")?)?;
    let mut reserved = BTreeSet::new();
    strings(&grammar["rules"], &mut reserved);
    let mut header = String::from(
        "// Generated by cargo run --example generate. Do not edit.\nstatic const char *const RESERVED_WORDS[] = {\n",
    );
    for word in reserved {
        header += &format!("  {},\n", serde_json::to_string(&word)?);
    }
    header += "};\n";
    update("src/reserved.h", &header, check)?;

    let data: Value = serde_json::from_str(&fs::read_to_string("data/builtins.json")?)?;
    let mut words = BTreeSet::new();
    for vocabulary in data["vocabularies"]
        .as_object()
        .ok_or("Missing vocabularies")?
        .values()
    {
        for word in vocabulary
            .as_array()
            .ok_or("Expected vocabulary word list")?
        {
            words.insert(word.as_str().ok_or("Expected builtin word")?);
        }
    }
    let mut query = String::from(
        "; Generated by cargo run --example generate. Edit highlights-base.scm instead.\n",
    );
    query += &fs::read_to_string("queries/highlights-base.scm")?;
    query += "\n; Builtin vocabulary words. Generated from data/builtins.json.\n((word) @function.builtin\n  (#is-not? local)\n  (#any-of? @function.builtin\n";
    for word in words {
        query += &format!("    {}\n", serde_json::to_string(word)?);
    }
    query += "))\n";
    update("queries/highlights.scm", &query, check)?;
    Ok(())
}
