/**
 * Factor's parser is extensible. These rules model the standard syntax and
 * preserve arbitrary vocabulary words without trying to resolve imports.
 * The scanner enforces whole-word boundaries and reads delimited text.
 */
module.exports = grammar({
  name: 'factor',

  externals: $ => [
    $.word, $.name, $._raw_name, $._effect_name, $._ffi_name, $._functor_name, $._list_name, $.number,
    $.string, $.raw_string, $.regexp, $.comment, $.shebang,
    $.character, $.collection_start, $.effect_start, $.quotation_start, $.string_body, $._error_sentinel,
  ],

  extras: $ => [/\s+/, $.comment],

  rules: {
    source_file: $ => seq(optional($.shebang), repeat($._form)),

    _form: $ => choice(
      $.word_defn, $.method_defn, $.generic_defn, $.syntax_defn,
      $.import_defn, $.tuple_defn, $.class_defn, $.predicate_defn,
      $.constructor_defn, $.instance_defn, $.symbol_defn,
      $.constant_defn, $.alias_defn, $.deferred_defn, $.main_defn,
      $.private_section, $.compile_time, $.ffi_defn, $.struct_defn, $.enum_defn,
      $.help_defn, $.article_defn, $.about_defn, $.named_string_defn,
      $.ebnf_defn, $.forget, $.directive_defn, $.functor_defn,
      $.com_interface, $.objc_class, $.watch, $.tip_defn, $.single_directive, $._expression,
    ),

    word_defn: $ => seq(
      field('kind', choice(':', '::', 'MACRO:', 'MACRO::', 'MEMO:', 'MEMO::',
        'IDENTITY-MEMO:', 'IDENTITY-MEMO::', 'TYPED:', 'TYPED::')),
      field('name', alias($._raw_name, $.name)),
      field('effect', $.stack_effect),
      optional(field('body', $.expression)), ';',
    ),
    method_defn: $ => choice(
      seq('M:', field('class', choice($.name, $.array)), field('name', alias($._raw_name, $.name)),
        optional(field('body', $.expression)), ';'),
      seq('M::', field('class', choice($.name, $.array)), field('name', alias($._raw_name, $.name)),
        field('effect', $.stack_effect), optional(field('body', $.expression)), ';'),
    ),
    generic_defn: $ => choice(
      seq(field('kind', choice('GENERIC:', 'MATH:', 'PRIMITIVE:', 'TAGS:')),
        field('name', alias($._raw_name, $.name)), field('effect', $.stack_effect)),
      seq('GENERIC#:', field('name', alias($._raw_name, $.name)),
        field('dispatch', $.number), field('effect', $.stack_effect)),
      seq('HOOK:', field('name', alias($._raw_name, $.name)),
        field('variable', $.name), field('effect', $.stack_effect)),
    ),
    syntax_defn: $ => seq('SYNTAX:', field('name', alias($._raw_name, $.name)),
      optional(field('body', $.expression)), ';'),

    import_defn: $ => choice(
      seq('USING:', repeat(field('vocabulary', alias($._list_name, $.name))), ';'),
      seq(field('kind', choice('USE:', 'UNUSE:', 'REUSE:', 'IN:', 'QUALIFIED:')),
        field('vocabulary', $.name)),
      seq('QUALIFIED-WITH:', field('vocabulary', $.name), field('prefix', $.name)),
      seq(field('kind', choice('FROM:', 'EXCLUDE:')), field('vocabulary', $.name),
        '=>', repeat(field('name', alias($._list_name, $.name))), ';'),
      seq('RENAME:', field('original', $.name), field('vocabulary', $.name),
        '=>', field('name', $.name)),
    ),

    tuple_defn: $ => seq(field('kind', choice('TUPLE:', 'ERROR:', 'BUILTIN:')),
      field('name', $.name), optional(seq('<', field('superclass', choice($.name, $.array)))),
      repeat(field('slot', choice($.name, alias('read-only', $.name), alias($.declaration, $.name), $.slot))), ';'),
    slot: $ => seq('{', field('name', alias($._raw_name, $.name)), optional(field('type', choice($.name, $.array))),
      repeat($.slot_attribute), '}'),
    slot_attribute: $ => choice('read-only', seq('initial:', field('value', $._expression)),
      seq('bits:', field('value', $.number))),
    class_defn: $ => choice(
      seq(field('kind', choice('MIXIN:', 'SINGLETON:')), field('name', $.name)),
      seq(field('kind', choice('UNION:', 'INTERSECTION:')),
        field('name', $.name), repeat(field('member', choice($.name, $.array, $.postpone))), ';'),
      seq('SINGLETONS:', repeat(field('name', alias($._list_name, $.name))), ';'),
    ),
    predicate_defn: $ => seq('PREDICATE:', field('name', $.name), '<',
      field('superclass', choice($.name, $.array)), optional(field('body', $.expression)), ';'),
    constructor_defn: $ => choice(
      seq('C:', field('name', $.name), field('class', choice($.name, $.array))),
      seq('CONSTRUCTOR:', field('name', $.name), field('class', choice($.name, $.array)),
        field('effect', $.stack_effect), optional(field('body', $.expression)), ';'),
    ),
    instance_defn: $ => seq('INSTANCE:', field('class', choice($.name, $.array)), field('mixin', $.name)),
    symbol_defn: $ => choice(
      seq(field('kind', choice('SYMBOL:', 'SLOT:')), field('name', alias($._raw_name, $.name))),
      seq('SYMBOLS:', repeat(field('name', alias($._list_name, $.name))), ';'),
    ),
    constant_defn: $ => seq(field('kind', choice('CONSTANT:', 'INITIALIZED-SYMBOL:')),
      field('name', alias($._raw_name, $.name)), field('value', $._expression)),
    alias_defn: $ => seq('ALIAS:', field('name', alias($._raw_name, $.name)), field('target', alias($._raw_name, $.name))),
    deferred_defn: $ => seq('DEFER:', field('name', alias($._raw_name, $.name))),
    main_defn: $ => seq(field('kind', choice('MAIN:', 'STARTUP-HOOK:', 'SHUTDOWN-HOOK:')),
      field('entry', choice($.word, $.quotation))),
    private_section: $ => seq('<PRIVATE', repeat($._form), 'PRIVATE>'),
    compile_time: $ => seq('<<', repeat($._form), '>>'),

    ffi_defn: $ => choice(
      seq(field('kind', choice('FUNCTION:', 'CALLBACK:', 'GL-FUNCTION:', 'X-FUNCTION:')),
        field('return_type', $.name), field('name', $.name),
        optional(field('extensions', $.array)), $.ffi_parameters),
      seq('FUNCTION-ALIAS:', field('name', $.name), field('return_type', $.name),
        field('foreign_name', $.name), $.ffi_parameters),
      seq('TYPEDEF:', field('type', choice($.name, $.array)), field('name', $.name)),
      seq(field('kind', choice('C-TYPE:', 'LIBRARY:')), field('name', $.name)),
      seq('C-GLOBAL:', field('type', $.name), field('name', $.name)),
      seq('C-LIBRARY:', field('name', $.name), field('platforms', $._expression)),
      seq('INITIALIZE-ALIEN:', field('name', $.name), optional(field('body', $.expression)), ';'),
    ),
    ffi_parameters: $ => seq('(', repeat(choice($.ffi_parameter, $.variadic)), ')'),
    ffi_parameter: $ => seq(field('type', $.name),
      field('name', alias($._ffi_name, $.name)), optional(',')),
    variadic: _ => '...',
    struct_defn: $ => seq(field('kind', choice('STRUCT:', 'PACKED-STRUCT:', 'UNION-STRUCT:', 'LE-STRUCT:', 'BE-STRUCT:', 'LE-PACKED-STRUCT:', 'BE-PACKED-STRUCT:')),
      field('name', $.name), repeat(field('slot', $.slot)), ';'),
    enum_defn: $ => seq('ENUM:', field('name', $.name),
      optional(seq('<', field('type', $.name))), repeat($.enum_member), ';'),
    enum_member: $ => choice($.name, seq('{', field('name', alias($._raw_name, $.name)), field('value', $._expression), '}')),
    help_defn: $ => seq('HELP:', field('name', alias($._raw_name, $.name)),
      optional(field('body', alias($._help_expression, $.expression))), ';'),
    article_defn: $ => seq('ARTICLE:', field('topic', $._expression), field('title', $._expression),
      optional(field('body', alias($._help_expression, $.expression))), ';'),
    about_defn: $ => seq('ABOUT:', field('topic', $._expression)),
    help_link: $ => prec.right(1, seq(field('kind', choice('$link', '$vocab-link', '$subsection')),
      field('target', $._expression))),
    help_references: $ => prec.right(seq(field('kind', choice('$subsections', '$see-also', '$related')),
      repeat($._expression))),
    named_string_defn: $ => seq('STRING:', field('name', $.name), field('body', $.string_body), ';'),
    ebnf_defn: $ => choice(
      seq('EBNF:', field('name', $.name), field('grammar', choice($.string, $.raw_string))),
      seq('PARTIAL-EBNF:', field('name', $.name), field('target', $.name)),
    ),
    forget: $ => seq('FORGET:', field('target', choice($.name, $.string, $.array))),
    alien_literal: $ => seq('ALIEN:', field('address', $.name)),
    vocabulary_literal: $ => seq('VOCAB:', field('name', $.name)),

    // Standard vocabulary definers whose bodies are ordinary Factor forms.
    directive_defn: $ => seq(field('kind', choice(
      'HINTS:', 'CONSULT:', 'BROADCAST:', 'PROTOCOL:', 'SLOT-PROTOCOL:',
      'TR:', 'MATCH-VARS:', 'SPECIALIZED-ARRAYS:', 'SPECIALIZED-VECTORS:',
      'INSN:', 'VREG-INSN:', 'FLUSHABLE-INSN:', 'FOLDABLE-INSN:',
      'REGISTERS:', 'HI-REGISTERS:', 'CATEGORY:', 'CATEGORY-NOT:',
      'XML-ERROR:', 'TAG:', 'CHLOE:',
      'METHOD-CHAIN:', 'LAZY:', 'LAZY::', 'RULE:', 'FUNCTOR-SYNTAX:',
      'MAIN-WINDOW:', 'SKIP-DEFINITIONS:', 'IMPLEMENT-STRUCTS:', 'FOREIGN-RECORDS:',
      'PEG:', 'PARTIAL-PEG:', 'BEFORE:', 'AFTER:',
    )), field('name', alias($._raw_name, $.name)), optional(field('body', $.expression)), ';'),
    functor_defn: $ => seq('<FUNCTOR:', field('name', alias($._raw_name, $.name)),
      field('effect', $.stack_effect), repeat($.functor_binding), 'WHERE',
      repeat($._form), ';FUNCTOR>'),
    functor_binding: $ => seq(field('name', alias($._functor_name, $.name)),
      field('value', choice($.quotation, seq(
        field('kind', choice('IS', 'DEFINES', 'DEFINES-PRIVATE', 'DEFINES-CLASS', 'DEFERS')),
        alias($._raw_name, $.name))))),
    com_interface: $ => seq('COM-INTERFACE:', field('name', $.name),
      field('superclass', $.name), field('guid', $.name), repeat($.com_method), ';'),
    com_method: $ => seq(field('return_type', $.name), field('name', $.name), $.ffi_parameters),
    objc_class: $ => seq('<CLASS:', field('name', $.name), '<',
      field('superclass', $.name), repeat(choice($.objc_method, $.cocoa_protocol)), ';CLASS>'),
    objc_method: $ => seq(field('kind', choice('METHOD:', 'CLASS-METHOD:')),
      field('return_type', $.name), field('name', $.name), repeat($.name), $.quotation, ';'),
    watch: $ => seq('<WATCH', repeat($._form), 'WATCH>'),

    tip_defn: $ => seq('TIP:', optional(field('body', alias($._help_expression, $.expression))), ';'),
    single_directive: $ => choice(
      seq(field('kind', choice('DESTRUCTOR:', 'GIR:', 'COCOA-PROTOCOL:', 'COMPONENT:')), field('name', $.name)),
      seq('XML-NS:', field('name', $.name), field('uri', $.name)),
      seq('FOREIGN-RECORD-TYPE:', field('name', $.name), field('type', $.name)),
    ),
    cocoa_protocol: $ => seq('COCOA-PROTOCOL:', field('name', $.name)),

    _help_expression: $ => repeat1(choice($._form, alias(')', $.word))),
    expression: $ => repeat1($._form),
    _expression: $ => choice(
      $.word, $.number, $.boolean, $.string, $.raw_string, $.regexp,
      $.character_literal, $.nan_literal, $.quotation, $.array,
      $.stack_effect, $.call_effect, $.word_literal, $.method_literal,
      $.postpone, $.local_binding, $.declaration, $.help_link, $.help_references,
      alias('<', $.word), alias('read-only', $.word), alias('initial:', $.word),
      alias('...', $.word), alias(',', $.word), alias('|', $.word),
      alias('=>', $.word), alias('bits:', $.word), alias('--', $.word),
      alias('$link', $.word), alias('$vocab-link', $.word), alias('$subsection', $.word), $.alien_literal, $.vocabulary_literal,
    ),
    boolean: _ => choice('t', 'f'),
    character_literal: $ => seq('CHAR:', $.character),
    nan_literal: $ => seq('NAN:', field('payload', $.name)),
    quotation: $ => choice(
      seq(field('open', choice('[', "'[", '$[', '[let', $.quotation_start)),
        optional(field('body', $.expression)), ']'),
      seq('[|', field('parameters', optional($.local_parameters)), '|',
        optional(field('body', $.expression)), ']'),
    ),
    local_parameters: $ => repeat1($.name),
    array: $ => seq(field('kind', $.collection_start), repeat($._form), '}'),
    word_literal: $ => seq(choice('\\', '$'), field('name', alias($._raw_name, $.name))),
    method_literal: $ => seq('M\\', field('class', choice($.name, $.array)), field('name', alias($._raw_name, $.name))),
    postpone: $ => seq('POSTPONE:', field('name', alias($._raw_name, $.name))),
    declaration: _ => choice('inline', 'recursive', 'flushable', 'foldable',
      'delimiter', 'deprecated', 'final', 'auto-use'),
    local_binding: $ => seq(':>', choice(field('name', $.name),
      seq('(', repeat(field('name', $.name)), ')'))),

    stack_effect: $ => seq('(', optional(field('inputs', $.effect)), '--',
      optional(field('outputs', $.effect)), ')'),
    call_effect: $ => seq(field('kind', $.effect_start),
      optional(field('inputs', $.effect)), '--', optional(field('outputs', $.effect)), ')'),
    effect: $ => repeat1($.effect_parameter),
    effect_parameter: $ => choice(
      prec.right(seq(field('name', alias($._effect_name, $.name)),
        optional(seq(':', field('type', choice($.word, $.stack_effect, $.array, $.boolean, $.number, $.word_literal)))))),
      seq(':', field('type', choice($.word, $.stack_effect, $.array, $.boolean, $.number, $.word_literal))),
    ),
  },
});
